fragment NewsParts on News {
  __typename
  items {
    __typename
    id
    title
    dateDisplay
    date
    text
    images {
      __typename
      src
      alt
    }
  }
}

fragment FussballParts on Fussball {
  __typename
  seasonEnd
  seasonEndMessage
  clubMatchesWidget
}
